# More options: https://starship.rs/config/

[character]
symbol = "➜"
error_symbol = "✗"
use_symbol_for_status = true

[directory]
truncation_length = 1
fish_style_pwd_dir_length=1

[python]
python_binary = "python3"
