# shellcheck disable=SC2148
###################
# Powerlevel9k
###################

export POWERLEVEL9K_SHOW_CHANGESET=true
export POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(root_indicator dir_writable context dir virtualenv vcs status)
export POWERLEVEL9K_ROOT_INDICATOR_BACKGROUND="red"
export POWERLEVEL9K_ROOT_INDICATOR_FOREGROUND="white"
export POWERLEVEL9K_PROMPT_ON_NEWLINE=false
export POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(pyenv)
export POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
export POWERLEVEL9K_STATUS_VERBOSE=false
export POWERLEVEL9K_SHORTEN_DELIMITER=""
export POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_right"
export POWERLEVEL9K_CHANGESET_HASH_LENGTH=6
