###################
# Powerlevel9k
###################

POWERLEVEL9K_SHOW_CHANGESET=true
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs status)
POWERLEVEL9K_PROMPT_ON_NEWLINE=false
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(virtualenv pyenv)
POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
POWERLEVEL9K_STATUS_VERBOSE=false
POWERLEVEL9K_SHORTEN_DELIMITER=""
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_right"
POWERLEVEL9K_CHANGESET_HASH_LENGTH=6
