- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.bashrc:
        force: true
        path: bashrc
    ~/.bash_profile: bash_profile
    # ~/.direnvrc: direnvrc
    ~/.dotfiles: ''
    ~/.gitignore_global: gitignore_global
    ~/.vim: vim
    ~/.tmux: tmux
    ~/.tmux.conf: tmux/.tmux.conf
    ~/.tmux.conf.local: tmux.conf
    ~/.vimrc: vimrc
    ~/.zsh: zsh
    ~/.zshrc:
      force: true
      path: zshrc

- shell:
    - ['zsh -c "mkdir -p $HOME/Projects/{test,github.com,gitlab.com}"', 'Setting up REPO directories... ']
    - ['git submodule update --init --recursive', 'Installing submodules... ']
    - ['git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf; ~/.fzf/install --all', 'Install fuzzy command-line finder (fzf)... ']
    - ['fonts/install.sh', 'Install powerline fonts... ']
    -
      command: ~/.dotfiles/bin/install_gitconfig.sh
      stdin: true
      stdout: true
      description: Configuring git...
